### ISSUE TITLE
Support 25Hz data read

### ISSUE THREAD

**Issue by jumarini** [ros-drivers/omron#11]
Thanks for your work on the Omron interface. My team is evaluating the viability of the OS32C for use in commercial indoor navigation.

We're only getting 12.9Hz, which seems to coincide with the 80ms dual-scan response time of the safety-rated outputs. Since a single scan only takes 40ms, can the driver publish the data at the advertised 25Hz rate? It would make navigation far more successful.

**Comment by timethy** [comment]
Hey @jumarini did you end up using the full 25 Hz rate?

**Comment by parthc-rob** [comment]
+1 It'd be great if you could give an update @jumarini

**Comment by timethy** [comment]
I actually managed to get the 25 Hz out, let me dig up my code and push if you are interested

**Comment by parthc-rob** [comment]
@timethy That'd be great, thanks so much!

**Comment by timethy** [comment]
Dear @parthc-rob 
As it's been over half a year now,
could you kindly check if my development branch
https://github.com/timethy/omron/tree/devel/timethy
helps?

I think it should be able to give you 25 Hz and slightly better precision as time-of-flight is given and conversion to range is done on the receiver side.

Also I think I reverted the angles because I think it was wrong, but maybe it was right, so please do check if it make sense.

If it works we can make a clean pull request into master.

**Comment by timethy** [comment]
I think the important lines [1] are these:
```
-  t_to_o.rpi = 0x00013070;
+  t_to_o.rpi = 40000; //0x00013070;
```

[1] https://github.com/ros-drivers/omron/compare/indigo-devel...timethy:devel/timethy#diff-9b8114ef90dc2ad6a4817210fcc60629L272

**Comment by reinzor** [comment]
Addressed in https://github.com/ros-drivers/omron/pull/18

**Comment by reinzor** [comment]
Covered by https://github.com/ros-drivers/omron/pull/24
